# generated by datamodel-codegen:
#   filename:  mydatamodel.yaml
#   timestamp: 2023-07-08T05:39:37+00:00

from __future__ import annotations

from pydantic import BaseModel


class Data(BaseModel):
    a: int
    b: int


class Model(BaseModel):
    data: Data
