# generated by datamodel-codegen:
#   filename:  mydatamodel.yaml
#   timestamp: 2023-07-08T05:40:44+00:00

from __future__ import annotations

from pydantic import BaseModel


class Data(BaseModel):
    a: int
    b: int


class MyModel(BaseModel):
    data: Data
