# require unicode support
FROM x11vnc/docker-desktop:zh_CN

RUN apt update
RUN apt install -y python3-dev

RUN pip3 install pynput mss

# copy recording required files to this image

COPY worker_gui.py /home/ubuntu/worker_gui.py