# require unicode support
FROM x11vnc/docker-desktop:zh_CN

COPY tsinghua_tuna_ubuntu_jammy_mirrors /etc/apt/sources.list
RUN rm /etc/apt/sources.list.d/mozillateam-ubuntu-ppa-jammy.list

RUN apt update
RUN apt install -y python3-dev

RUN pip3 install pynput mss

# copy recording required files to this image

COPY worker_gui.py /home/ubuntu/worker_gui.py